### ISSUE TITLE
PROBLEM & SOLUTION Widely reported issue of draftback not working: wheel keeps spinning and doesn't work.

### ISSUE THREAD

**Issue by zoplonix** [jsomers/draftback#2]
See here for people complaining: https://chrome.google.com/webstore/detail/draftback/nnajoiemfpldioamchanognpjmocgkbg/support

Issue: When one navigates to a Google Doc and clicks the Draftback button nothing happens. The wheel keeps spinning (where it shows how many revisions are in the document)

Cause: When using Google Accounts and logged into multiple accounts at once, the url for the `Changelog` and `RevisionCount` is different - `...docs.google.com/u/X/d/...` - where `X` is a number representing the currently logged in google account. Currently the code is looking for the `Changelog/RevisionCount` at `...docs.google.com/d/...`

Solution: Modify the beginning of these two functions to get the proper URL if the person happens to be using multiple logins (still researching, thoughts?)

    getChangelog: function() {
        var regmatch = location.href.match(/^(https:\/\/docs\.google\.com.*?\/document\/d\/)/)

    getRevisionCount: function() {
        var regmatch = location.href.match(/^(https:\/\/docs\.google\.com.*?\/document\/d\/)/)

**Comment by jsomers** [comment]
@zoplonix Thanks for the report! This is very helpful -- I'm glad someone finally got to the bottom of this.

Is it fairly straightforward to reproduce the scenario you're talking about? I.e., do you have steps for what it means to be "using Google Accounts and logged into multiple accounts at once"?

Thanks again.

**Comment by zoplonix** [comment]
https://support.google.com/accounts/answer/1721977?hl=en

**Comment by jsomers** [comment]
@zoplonix I just pushed a fix -- would you mind testing once you see v. 0.11? It might be a little bit before you can see it. Thanks

**Comment by zoplonix** [comment]
Works perfectly thanks!
